### ISSUE TITLE
please make this work in modular, non-nodejs environment

### ISSUE THREAD

**Issue by tomprogers** [linaGirl/ee-aws-v4-signature#1]
This package won't work outside of a nodejs environment, because at least one of its dependencies is only available in node ('crypto'). That means people building web-based native mobile apps can't use it.

**Comment by linaGirl** [comment]
the module is only used in the node environment and more or less deprecated. i have no plans to upgrade it for other environments. this module was created for the time when the aws sdk was so crappy that i didn't want to use it in my projects.

meanwhile the aws sdk should be stable, of good quality and available in almost any environment.
